POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title" : "First Artificial Enzyme From Two Non-Biological Groups Created",
    "author" : "sb admin",
    "url" : "https://scienceblogs.com/sb-admin/2020/02/10/first-artificial-enzyme-two-non-biological-groups-created-151440",
    "likes" : 0
}