POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title" : "I Am a Quantumist: Bring it On!",
    "author" : "pontiff",
    "url" : "https://scienceblogs.com/pontiff/2007/11/14/i-am-a-quantumist-bring-it-on",
    "likes" : 0
}